### ISSUE TITLE
Formatting posts

### ISSUE THREAD

**Issue by lecorreia** [ncarll/literallylenny#13]
I don't think this is really something YOU can do, but it bothers me and i'll write a ticket anyways. I want the text on posts to have a set width so they don't go all over the page. I don't want the text to go underneath the photo.

**Comment by ncarll** [comment]
@lecorreia As we discussed, I will try giving you a table template that you can put in the post on your side.  I think that will be the best way to alter the page formatting reliably.

**Comment by ncarll** [comment]
Closing this because the fix put in from the editor seems to be working for now
