### ISSUE TITLE
Move Stars

### ISSUE THREAD

**Issue by lecorreia** [ncarll/literallylenny#18]
Id like to move the stars over so that they're centered with the image (see "As She Fades". (I put it in with the table already, yay me!)

![image](https://user-images.githubusercontent.com/39041562/39962262-4e1db6c2-5617-11e8-881b-3c9db005e9d8.png)

**Comment by ncarll** [comment]
@lecorreia This is a fix on the editor side.  Maybe we can come up with a better layout for entering the custom divs that would make this easier to do on the fly.  For now, I edited the layout myself to correct, but this is a manual process for each post.
